FROM sh-harbor.mthreads.com/mt-ai/vits:v1.0
LABEL maintainer="<yi.liu@mthreads.com>"
ENV DEBIAN_FRONTEND=noninteractive
# RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple gradio
WORKDIR /workspace/vits
